In [9]:
import numpy as np

a = np.array([1,2,3], dtype = "int 16")
print(a)

[1 2 3]


In [10]:
b = np.array([[1.2,1.4,1.5],[2,4,7]])
print(b)

[[1.2 1.4 1.5]
 [2.  4.  7. ]]


In [15]:
a.shape

(3,)

In [16]:
b.shape

(2, 3)

In [13]:
a.ndim

1

In [14]:
b.ndim

2

In [27]:
a.dtype

dtype('int64')

In [22]:
b.dtype

dtype('float64')

In [29]:
a.itemsize

8

In [28]:
b.itemsize

8

In [31]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [35]:
c[0,3]
c[1,5]

np.int64(13)

In [37]:
c[0,:]
c[:,3]

array([ 4, 11])

In [38]:
c[0, 0:5:2]

array([1, 3, 5])

In [41]:
c[0,1] = 5
print(c)

[[ 1  5  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [42]:
c[0,:] = 5
print(c)

[[ 5  5  5  5  5  5  5]
 [ 8  9 10 11 12 13 14]]


In [43]:
c[0,:] = [9,8,7,6,5,4,3]
print(c)

[[ 9  8  7  6  5  4  3]
 [ 8  9 10 11 12 13 14]]


In [44]:
c[:,2] = 5
print(c)

[[ 9  8  5  6  5  4  3]
 [ 8  9  5 11 12 13 14]]


In [47]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [48]:
d[1,0,1]

np.int64(6)

In [49]:
d[:,:,1]

array([[2, 4],
       [6, 8]])

In [50]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [52]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
np.zeros((4,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [55]:
np.ones((3,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [13]:
np.random.rand(2,4)

NameError: name 'np' is not defined