In [1]:
import numpy as np
from matplotlib.pyplot import axis

np.full((2,2),4)

array([[4, 4],
       [4, 4]])

In [3]:
np.random.rand(3,3,3)

array([[[0.10711954, 0.93649324, 0.68339889],
        [0.51128074, 0.51557574, 0.75361444],
        [0.82357504, 0.67116987, 0.30046058]],

       [[0.3188091 , 0.08219653, 0.14744055],
        [0.70118752, 0.59971065, 0.14859358],
        [0.31382955, 0.29506479, 0.18550729]],

       [[0.759929  , 0.31705514, 0.70935894],
        [0.270088  , 0.29853053, 0.14271904],
        [0.86605431, 0.73668051, 0.26282954]]])

In [4]:
np.random.randint(4,size=(2,2))

array([[1, 2],
       [2, 0]], dtype=int32)

In [5]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
arr = np.array([[1,2,3]])
a1 = np.repeat(arr,3,axis=1)
print(a1)

[[1 1 1 2 2 2 3 3 3]]


In [5]:
arr = np.array([[1,2,3]])
a1 = np.repeat(arr,3,axis=0)
print(a1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [30]:
a = np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [34]:
a[1:4, 1:4] = 0
#print(a)
a[2,2] = 9
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [38]:
a = np.array([1,2,3])
a += 2
a

array([3, 4, 5])

In [40]:
a -= 2
a

array([-1,  0,  1])

In [41]:
a *= 2
a

array([-2,  0,  2])

In [45]:
a / 2
a

array([-2,  0,  2])

In [48]:
a = a ** 2
print(a)

[4 0 4]


In [50]:
a = np.array([1,2,3,4])
b = a.copy()
print(a)

[1 2 3 4]


In [51]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [57]:
a = np.ones((2,3))
print(a)

b = np.full((3,2) , 2)
print(b)

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [58]:
# finding the determinate
a = np.identity(3)
np.linalg.det(a)

np.float64(1.0)

In [59]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [63]:
np.min(a,axis=1)


array([1, 4])

In [64]:
np.sum(a)

np.int64(21)

In [70]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [73]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
h1 = np.ones((2,4))
h2 = np.full((2,2), 2)
np.hstack([h1,h2])

array([[1., 1., 1., 1., 2., 2.],
       [1., 1., 1., 1., 2., 2.]])

In [23]:
file_data = np.genfromtxt("data.txt",delimiter=",")
file_data = file_data.astype('int32')
print(file_data)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [29]:
np.any(file_data >50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [30]:
((file_data>50) & (file_data<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [31]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [33]:
a[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [42]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [51]:
a[[0,4,5],3:5:1]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [ ]:
[]